name: coderco secrets 

on: [push] 

jobs : 
  build: 
    runs-on: ubuntu-latest 


    steps: 
    - name: checkout code 
      uses: actions/checkout@v2 


    - name: use secret 
      run: echo " The secret is ${{ secrets.MY_SECRETS}}"
      

    - name: use secret in env variable 
      env: 
       MY_SECRETS: ${{ secrets.MY_SECRETS }}
      run: echo "The secret is $MY_SECRETS"
